# Generated by Django 4.2.3 on 2023-08-31 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("robodoc", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="map",
            name="desc",
            field=models.CharField(default="", max_length=500),
        ),
    ]
