# Generated by Django 4.2.3 on 2023-08-31 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("robodoc", "0002_map_desc"),
    ]

    operations = [
        migrations.AddField(
            model_name="map",
            name="map_file",
            field=models.FileField(default="", upload_to="images/maps"),
        ),
    ]
