# Generated by Django 4.2.3 on 2023-08-31 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("robodoc", "0003_map_map_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section", name="code", field=models.SlugField(),
        ),
    ]
