# Generated by Django 4.2.3 on 2023-08-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roboplus", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="app", name="prompt", field=models.TextField(default=""),
        ),
    ]
