# Generated by Django 4.2.3 on 2023-08-31 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roboplus", "0002_app_prompt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="app",
            name="icon",
            field=models.CharField(default="bi-app", max_length=50),
        ),
    ]
