# Generated by Django 4.1.1 on 2022-09-10 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_remove_user_name"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="username",),
    ]
