# Generated by Django 4.1.1 on 2022-09-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_remove_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.IntegerField(
                choices=[(0, "user"), (1, "moderator")], default=0
            ),
        ),
    ]
