# Generated by Django 4.1.1 on 2023-03-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_user_block_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="question_categories",
            field=models.TextField(default="", max_length=1000),
        ),
    ]
