# Generated by Django 4.2.3 on 2023-08-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roboprompt", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="tags",
            field=models.CharField(default="", max_length=250),
        ),
    ]
