# Generated by Django 4.2.3 on 2023-08-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=150)),
                ("about", models.CharField(default="", max_length=500)),
                ("desc", models.TextField(default="", max_length=10500)),
                ("banner", models.FileField(upload_to="images/banners/")),
                ("logo", models.FileField(upload_to="images/logos/")),
                ("link", models.CharField(default="", max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=150)),
                ("tools", models.ManyToManyField(to="directory.tool")),
            ],
        ),
    ]
