# Generated by Django 4.2.3 on 2023-08-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("directory", "0002_tool_tags_delete_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tool",
            name="logo",
            field=models.FileField(default="", upload_to="images/logos/"),
        ),
    ]
